kind: Pod
apiVersion: v1
metadata:
  name: nameapp
  labels:
    type: nameapp
spec:
  containers:
  - name: nameapp
    image: thecasualcoder/dobby
    ports:
    - containerPort: 4444
    env:
    - name: NAME
      valueFrom:
        configMapKeyRef:
          name: special-config
          key: name
    - name: SECRET_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: password