apiVersion: batch/v1
kind: Job
metadata:
  name: job-example
spec:
  ttlSecondsAfterFinished: 100
  backoffLimit: 3
  activeDeadlineSeconds: 50
  completions: 3
  parallelism: 2
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: main
        image: docker.io/library/bash:5
        command: ["bash"]        
        args:
        - -c
        - echo "Hello world!" && sleep 5 && exit 1