apiVersion: v1
kind: Pod
metadata:
 name: nginx
spec:
 volumes:
 - name: html
   emptyDir: {}
 containers:
 - name: nginx
   image: nginx
   ports:
   - containerPort: 80
   volumeMounts:
   - name: html
     mountPath: /usr/share/nginx/html
