apiVersion: v1
kind: Pod
metadata:
 name: multi-container
spec:
 volumes:
 - name: html
   hostPath:
     path: /home/docker/data/node-host-path
     type: Directory
 containers:
 - name: c1
   image: nginx
   ports:
   - containerPort: 80
   volumeMounts:
   - name: html
     mountPath: /usr/share/nginx/html
